[package]
name = "rust-advent-of-code-2018"
version = "0.1.0"
authors = ["cfiet"]
edition = "2018"

[features]
day1 = []
day2 = []
day3 = []
day4 = []
all = ["day1", "day2", "day3", "day4"]
default = ["all"]

[dependencies]
regex = "*"
lazy_static = "*"
chrono = "*"
time = "*"